### ISSUE TITLE
when will the repo be stable?

### ISSUE THREAD

**Issue by zqh0253** [Skylark0924/advanced_robotics_project#1]
Dear tutors,

It seems that this repo is being updated frequently after the release. I am wondering when will we get a stable version?
I am worried that current works on this version may not be compatible with your future updated versions, or there may be still some bugs in this version.

**Comment by Skylark0924** [comment]
Hi, I am sorry for the frequent update today. I've made and recorded the demo video today, so there won't be any major code changes after that.

**Comment by Skylark0924** [comment]
To be mentioned, I just changed some python scripts today, which have nothing to do with the installation process. And the demo video demonstrates that this repo is feasible, thus, you can install it with confidence.
