### ISSUE TITLE
Installation problem in Step 9

### ISSUE THREAD

**Issue by SingaChen** [Skylark0924/advanced_robotics_project#2]
Hi Junjia,
I am trying to install the simulator in my PC and everything goes well before step 9. 

When I run the command "sudo bash tools/create_container.sh", It is shown that "non-network local connections being added to access control list". Is that formal?

I also noticed that I should modify the name and path in the scripts. Sorry for my unskilled operation, I do not know how to do it. I would appreciate you very much if you can help me with it!

Thanks in advanced!

**Comment by Skylark0924** [comment]
> When I run the command "sudo bash tools/create_container.sh", It is shown that "non-network local connections being added to access control list". Is that formal?

Hi, that is just output information, not an error or warning. So you do not need to care about it.

**Comment by Skylark0924** [comment]
> I also noticed that I should modify the name and path in the scripts. Sorry for my unskilled operation, I do not know how to do it. I would appreciate you very much if you can help me with it!

In the `create_container.sh`:
![image](https://user-images.githubusercontent.com/24936522/144018607-12982d58-128e-4ddb-a17e-4b72768a409c.png)
You need to change `$HOME/Github/advanced_robotics_project` to the path where you clone the repository. The others do not need to be changed.

**Comment by SingaChen** [comment]
> 

Thanks for your help, I did it and jumped to Step 10.

However, the directory is not existing when I send "cd /root/ocrtoc_ws/src/tools" after I enter the docker container.
![Screenshot from 2021-11-30 17-26-28](https://user-images.githubusercontent.com/65845804/144020866-e39e0747-79ce-4f6e-ae91-c83e04c7ca9f.png)

**Comment by Skylark0924** [comment]
That's why you need to change the path (before create_container).

So what you need to do is:
1. change the path
2. create the container again

**Comment by Skylark0924** [comment]
Is your problem solved？If it is solved, I will close this issue.

**Comment by SingaChen** [comment]
Thanks for your consideration, it is solved now~
