### ISSUE TITLE
Could not start manipulator interface node

### ISSUE THREAD

**Issue by weeshen0405** [Skylark0924/advanced_robotics_project#3]
Hi, i get error when i try to start the manipulator interface node.
![Screenshot 2021-12-03 11:51:34](https://user-images.githubusercontent.com/95459231/144542474-db08e7f2-1a78-4f2b-8f1c-1aa244127b07.png)

**Comment by Skylark0924** [comment]
You might forgot to setup by following [Step10](https://github.com/Skylark0924/advanced_robotics_project#set-up-environment-inside-the-docker-container).

**Comment by weeshen0405** [comment]
i tried doing step10 again and it is the same.
I remember it used to work when I first setup, but not sure what have changed and now it stop working. I can still run pybullet and rviz

**Comment by Skylark0924** [comment]
Could you run the test_dsr_traj_vis.py script？

**Comment by weeshen0405** [comment]
yes i can run that, but not test_fk_ik.py

**Comment by Skylark0924** [comment]
That's weird. Could you try to stop the docker and restart it?

**Comment by weeshen0405** [comment]
yes, i tried that too. can i go find you in ab1 2f?

**Comment by Skylark0924** [comment]
Sure, about 2pm？

**Comment by weeshen0405** [comment]
Maybe after 3pm

**Comment by Skylark0924** [comment]
Ok

**Comment by Skylark0924** [comment]
The problem is solved by running the following script in the docker:
```
source ~/.bashrc
```
