### ISSUE TITLE
Orientation and joint angle limit

### ISSUE THREAD

**Issue by weeshen0405** [Skylark0924/advanced_robotics_project#4]
Do we need to care about the orientation of the end effector?
I notice the joint trajectories that I generated will hit the joint limit, how can I solve this issue

**Comment by Skylark0924** [comment]
Hi, to make the  project easier, orientation is not considered. If you are using the desired trajectory, it might not reach the joint limit, maybe you can try to change the initial position.

**Comment by weeshen0405** [comment]
I know the desired trajectory is within the workspace, but when I use Newton approach for generating joint trajectories, I get joint angles exceed the joint limit.
I wonder which method you use to generate the joint trajectories in this demo?
https://github.com/Skylark0924/advanced_robotics_project/blob/master/docs/final2.gif

**Comment by Skylark0924** [comment]
Hi, in that demo, I didn't solve the inverse kinematics but calculated the inversion of differential kinematics just like the reference python script of hw2.
